server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qas #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.133:3306/tensquare_qa?characterEncoding=UTF8
    username: root
    password: 6680124
  jpa: 
    database: MySQL
    show-sql: true
jwt:
  config:
    key: choibin

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true