server: 
  port: 9008

spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.133:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: 6680124
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.25.133
  rabbitmq:
    host: 192.168.25.133

jwt:
  config:
    key: choibin
    ttl: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
